#name: learn-github-actions
#on: [push]
#jobs:
#  check-bats-version:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - run: npm install -g bats
#      - run: bats -v
#
#  hannah-test-job:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - run: echo "Hello World!"

# source: https://dev.to/goodidea/setting-up-pm2-ci-deployments-with-github-actions-1494

name: CI - Master
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # run tests
      - name: set up SSH
        run: |
          mkdir -p ~/.ssh/
          cp $SSH_PRIVATE_KEY ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
          eval `ssh-agent -s`
          ssh-keygen -yf ~/.ssh/id_rsa >> ~/.ssh/id_rsa.pub
          ssh-add ~/.ssh/id_rsa
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Install PM2
        run: sudo npm i -g pm2

      - name: Deploy
        run: pm2 deploy sand update